notaryproject/notation-go

crypto/timestamp/http_test.go, crypto/timestamp/token.go, internal/crypto/cms/signed.go, internal/crypto/cms/signed_test.go, signature/jws/signer.go, signature/jws/signer_test.go, signature/jws/verifier.go, signature/jws/verifier_test.go
All verification options, except configurating the root certificate pool, are hidden from the timestamp token verifiers.
Resolves #16.
=> Restrict TSA verify options

crypto/timestamp/http_test.go, crypto/timestamp/request.go, crypto/timestamp/response.go, crypto/timestamp/timestamptest/tsa.go, crypto/timestamp/timestamptest/tsa_test.go, crypto/timestamp/token.go, go.mod, internal/crypto/cms/signed.go, notation.go, signature/jws/signer.go, signature/jws/signer_test.go, signature/jws/spec.go, signature/jws/verifier.go, signature/jws/verifier_test.go
Rename go module from `github.com/notaryproject/notation-go-lib` to `github.com/notaryproject/notation-go` by #33
=> Rename go module

verification/policy.go, verification/policy_test.go
* Implementing a parser for trust policy documents as specified in https://github.com/notaryproject/notaryproject/pull/149/files?short_path=bab1489#diff-bab14897801fe47838fadd7f0ebd867e81ce66e098785175f4c1ec368bbe406a
* Added unit tests and manually tested locally 
cc: @shizhMSFT @SteveLasker
=> Load and Validate Trust Policy documents

notation.go, plugin/metadata.go, plugin/plugin.go, signature/jws/algorithm.go, signature/jws/plugin.go, signature/jws/plugin_test.go, signature/jws/signer.go, signature/jws/verifier.go
This PR implements the `generate-envelope` workflow by reusing most of the `PluginSigner` logic.
=> Implement generate-envelope workflow

verification/helpers.go, verification/policy.go, verification/policy_test.go
Followed the rules from https://github.com/notaryproject/notaryproject/blob/main/trust-store-trust-policy-specification.md#selecting-a-trust-policy-based-on-artifact-uri
Signed-off-by: rgnote <5878554+rgnote@users.noreply.github.com>
=> Add GetApplicableTrustPolicy function

go.mod, go.sum, registry/interface.go, registry/repository.go
This PR refactors to use the new method `PackArtifact` to pack and push the signature manifest as mentioned in https://github.com/oras-project/oras-go/issues/175#issuecomment-1168158460
Signed-off-by: Binbin Li <libinbin@microsoft.com>
=> feat: Use PackArtifact to push signature manifest

go.mod, go.sum, signature/plugin.go, signature/plugin_test.go, signature/signer.go
Updates to accommodate changes as part of https://github.com/notaryproject/notation-core-go/pull/17
- Closes https://github.com/notaryproject/roadmap/issues/28
=> Updates based on signing scheme update in notation-go-core

go.mod, go.sum, notation.go, plugin/plugin.go, signature/algorithm.go, signature/plugin.go, signature/plugin_test.go, signature/provider.go, signature/signer.go, signature/signer_test.go, signature/verifier_test.go
Refactor notation-go to support cose signature
1. plugin/plugin.go: Add some fields to the plugin contract struct to better support new interface. Need to update when new spec is ready.
2. signature/algorithm.go: Add `tostring` method for keyspec and hash function. Need to update when new spec is ready. If we don't need hash and keyspec in signing request, it can be deprecated.
3. signature/provider.go: A combination of original signature provider and runner. It implements runner and signer interface. For built-in provider, it use `LocalSigner` from `notation-core-go`. For external provider, it implements `signer` interface by using runner to interact with external plugin (sending`describle key` and `generate signature` request)
5. …
=> refactor: refactor signer to support cose signature

dir/fs.go, dir/fs_test.go, dir/path.go, dir/path_test.go
1. GetPath logic: if the given path doesn't exist, return the first
possible path in the union directories, so when create a new file the
UnionDirFS will select user directory which was provided as the first
directory when create the UnionDirFS
2. change the constant name
=> fix: dir package optimize

go.mod, go.sum
Updated dependencies:
- `oras-go`: `v2.0.0-rc.1.0.20220727034506-eb13fdfeefa6` -> `v2.0.0-rc.2`
- `notation-core-go`: `v0.0.0-20220809210532-f0a54093ba32` -> `v0.1.0-alpha.3`
Signed-off-by: Shiwei Zhang <shizh@microsoft.com>
=> build: bump dependencies

go.mod, go.sum, plugin/plugin.go, signature/algorithm.go, signature/algorithm_test.go, signature/envelope.go, signature/plugin.go, signature/plugin_test.go, signature/provider.go, signature/provider_test.go, signature/signer_test.go, signature/verifier_test.go
1. Add more signer and verifier tests (test signer/verifier from file)
2. Update algorithm according to new [spec](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md)
3. Add provider test
```
go test ./signature -cover -count=1   
ok      github.com/notaryproject/notation-go/signature  6.153s  coverage: 87.4% of statements
```
=> test:add signer,verifer,provider,algorithm unit tests

go.mod, go.sum, plugin/plugin.go, signature/algorithm.go, signature/algorithm_test.go, signature/envelope.go, signature/plugin.go, signature/plugin_test.go, signature/provider.go, signature/provider_test.go, signature/signer_test.go, signature/verifier_test.go
1. Support new plugin spec(mainly new algorithm and hash name)
2. Sign with payload instead of hash
3. Update sign request and signer interface
4. A better mock plugin provider for test
5. Add more unit test
```
go test ./signature -cover -count=1
ok      github.com/notaryproject/notation-go/signature  11.247s coverage: 88.5% of statements
```
=> refactor:support cose and new plugin spec

go.mod, go.sum, plugin/plugin.go, signature/plugin_test.go, signature/provider_test.go, verification/helpers_test.go, verification/types.go, verification/verifier_helpers.go, verification/verifier_test.go
1. Remove `VerificationPlugin` and `VerificationPluginMinVersion` from plugin's critical attribute
2. Fix broken tests (mostly error msg changes)
=> fix:fix broken verification unit tests

dir/fs.go
This PR targets the dev-rc.1 branch only.
ListAllPath is created for Notation CLI's 'notation cert list' command.
=> update: added ListAllPath to UnionDirFS interface

config/base.go, config/config.go, config/config_test.go, config/keys.go, config/keys_test.go, config/testdata/config.json, dir/base.go, dir/path.go, dir/path_test.go
1. config add `EnvelopeType` argument
2. dir package optimize: allow user define `WriteLevel` = UserLevel | SystemLevel
3. add ConfigForWrite(), TrustStoreForWrite(), TrustPolicyForWrite() func to get writable path
4. refector `config` pacakge: receive a `path` argument when load and save file to allow user to overwrite the default directory structure
=> feat: dir package allows user to define user/system write level

config/config.go, config/keys.go
change the config load & save function's `path` parameter to be a single string value instead of an array of string.
=> fix: optimize config package

verification/errors.go, verification/policy.go, verification/policy_file_processor.go
Defined and implemented functions to support CRUD on the policy file.
This PR just adds the basic support. We'll need another PR to refactor it to integrate with the current config read/write module.
Did manually tests with PR: https://github.com/notaryproject/notation/pull/333. Will add unit tests in another PR.
Signed-off-by: Binbin Li <libinbin@microsoft.com>
=> feat: support CRUD on TrustPolicy

go.mod, go.sum
Switch to notation-core-go main branch.
Signed-off-by: Binbin Li <libinbin@microsoft.com>
=> build: update notation-core-go to use main branch

verification/verifier_helpers.go, verification/verifier_helpers_test.go
Fix the issue:
previously the identity parameter format was not checked. The following identity config causes a runtime error.
```
trustpolicy.json
{...
"trustedIdentities": [
"CN=wabbit-networks.io,O=Notary,L=Seattle,ST=WA,C=US"
]
...
}
```
Test:
add unit test
=> fix: trustpolicy identity malformed check

config/config.go, config/config_test.go, config/testdata/config.json
Add `EnvelopeType` parameter in config.json file
Resolves: https://github.com/notaryproject/notation/issues/325
=> feat: add envelope type config

go.mod, go.sum, plugin/plugin.go, verification/helpers.go, verification/verifier.go, verification/verifier_helpers.go, verification/verifier_test.go
This PR bumps up notation-core-go. Since extended attribute key type is changed to interface{}, notation-go code needs to be updated accordingly.
=> update: bump up notation-core-go

internal/mock/mocks.go, plugin/plugin.go, verification/verifier_helpers.go
Temporary fix for https://github.com/notaryproject/notation-core-go/issues/88
Signed-off-by: rgnote <5878554+rgnote@users.noreply.github.com>
=> Fix VerifySignature command json marshaling

verifier/helpers.go, verifier/helpers_test.go, verifier/verifier.go, verifier/verifier_test.go
This PR fixed the verifier constructor design.
Previously, verifier constructor only takes in trust policy document and plugin manager.
Currently, it also takes in trustStore of type truststore.X509TrustStore.
This PR fixed #205.
=> update: updated verifier design

go.mod, go.sum, registry/repository.go
This PR upgrades notation-go to use oras-go v2.0.0-rc.5.
Main change: ReferrerFinder is added into registry.Repository interface.
=> update: upgraded to oras-go v2.0.0-rc.5

internal/file/file.go, verifier/helpers.go, verifier/trustpolicy/trustpolicy.go, verifier/trustpolicy/trustpolicy_test.go, verifier/truststore/truststore.go, verifier/verifier.go, verifier/verifier_test.go
This PR scans for strings.Index() in notation-go and replaced it with strings.Cut.
It also adds checks on outputs of strings.Cut based on the specs.
Resolves #204.
=> update: replaced strings.Index with strings.Cut

internal/mock/mockfs/fs.go, internal/mock/mocks.go, plugin/integration_test.go, plugin/manager.go, plugin/manager_test.go, plugin/plugin.go, plugin/plugin_test.go, plugin/proto/metadata.go, plugin/proto/metadata_test.go, plugin/testdata/main.go, signer/plugin.go, verifier/helpers.go, verifier/verifier.go
- Add ContractVersion argument when executing plugin request
- Check ContractVersion when getting plugin metadata
- Moved the path existence check from manager.Get() to NewCLIPlugin()
Test:
Added invalid contract version unit test.
=> fix: update plugin to add ContractVersion

notation.go, notation_test.go
In this PR:
1. Created RemoteVerifyOptions for notation.Verify(), and therefore, VerifyOptions is now only for verifier.Verify().
2. In notation.Verify(), using signature media type fetched from registry.
=> update: check SignatureMediaType in notation.Verify

plugin/integration_test.go, signer/signer_test.go, verifier/trustpolicy/trustpolicy_test.go
Since we are not implementing system config behavior in rc1, updating code to have only user(r,w,x) permission.
Also, its a good practice to use minimum permission model
=> Use minimum(user only) file permissions

go.mod, go.sum
Bump up to use the most recent notation-core-go.
=> update: bump up dependencies

notation.go, notation_test.go, signer/plugin_test.go, signer/signer_test.go
This PR adds tag reference logs in notation.Sign and notation.Verify.
=> feat: added tag reference log for notation.Sign and notation.Verify

notation.go, notation_test.go, plugin/proto/sign.go, signer/plugin.go, signer/plugin_test.go, signer/signer.go, signer/signer_test.go
There will be two PRs, one in notation-go([PR#222](https://github.com/notaryproject/notation-go/pull/222)) and other in notation([PR#458](https://github.com/notaryproject/notation/pull/458)) repo.
*Tests are failing because this PR depends on https://github.com/notaryproject/notation-go/pull/222*
Issue: https://github.com/notaryproject/notation/issues/443
=> Pass expiry to envelope-generator plugin

notation.go, signer/plugin.go, signer/plugin_test.go, signer/signer.go, signer/signer_test.go
Addresses TODO's tracked in [Issue 80](https://github.com/notaryproject/notation-go/issues/80)
- Note that new tests for NewSignerFromFiles were already added back [in September](https://github.com/notaryproject/notation-go/commit/2bcfd343f974938e8eeb76e233bc2526e0c36061)
- Validations around no top-level attributes being added are from [5.c.c](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md#signing-workflow-using-plugin-1) in the spec
Signed-off-by: Jonathan Donas <jddonas@amazon.com>
=> Add additional header validation for payload

go.mod, go.sum
All PRs in notation-core-go are merged. Updating dependency in notation-go.
=> update: bump up notation-core-go in notation-go

registry/mediatype.go, registry/repository_test.go
This PR changes the notation artifact type from `application/vnd.cncf.notary.v2.signature` to `application/vnd.cncf.notary.signature`.
=> fix: updated notation artifact type to application/vnd.cncf.notary.signature

notation.go, signer/plugin.go, verifier/trustpolicy/trustpolicy.go, verifier/trustpolicy/trustpolicy_test.go, verifier/verifier.go
This PR adds more logs to the library and improves error messages.
This PR intends to resolve following issues:
https://github.com/notaryproject/notation/issues/462
https://github.com/notaryproject/notation/issues/128 -> comments related to trust policy
=> update: logs and error messages

plugin/plugin.go, plugin/plugin_test.go
Fix error message: Instead of printing bytes in error message convert them to string.
=> Fix error message

config/keys_test.go
Adds more unit test for keys.go
=> Adds more unit test for keys.go

errors.go, notation.go
This PR adds a `ErrorPushSignatureFailed` error type so that users of notation.Sign() would be able to check error type on Signing failures. 
On notation CLI side, if the error is of type `ErrorPushSignatureFailed`, a suggestion of using OCI image manifest will be printed out.
=> Update: added ErrorPushSignatureFailed

config/keys.go, config/keys_test.go, errors.go, internal/pkix/pkix.go, notation.go, notation_test.go, plugin/manager_test.go, plugin/plugin.go, plugin/proto/verify.go, signer/plugin.go, verifier/helpers.go, verifier/trustpolicy/trustpolicy.go, verifier/verifier.go
go fmt.
Cleaned up comments format.
Removed unused code in unit tests.
=> chore: clean up comments format and removed unused code

go.mod, go.sum, signer/plugin_test.go, signer/signer_test.go
Update notation-core-go dependency
=> bump: update notation-core-go dependency

notation.go
When signing with metadata, notation needs adds the metadata in signature blob as descriptor's annotation but it looks like we are also added it to image-manifest's subject's descriptor, which is undesirable. This PR removes user-metadata from manifest's subject annotations
```bash
notation sign %IMAGE% --user-metadata name=pmt
```
```
{
"schemaVersion": 2,
"mediaType": "application/vnd.oci.image.manifest.v1+json",
"config": {
"mediaType": "application/vnd.cncf.notary.signature",
"digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
"size": 2
},
"layers": [
{
"mediaType": "application/jose+json",
"digest": "sha256:73a6eda31ccc00fc2b8058b79d728429246feebf790f877a0df6b57a0fcd86ad",
"size": 4931
}
],
"subject": {
"mediaType": …
```
=> fix: don't add user-metadata to manifest's subject annotations

verifier/trustpolicy/trustpolicy.go, verifier/trustpolicy/trustpolicy_test.go
This PR rephrased error message returned during trust policy verification.
=> chore: update err msg for policy verification

go.mod, go.sum
Updating notation-core-go dependency to rc.3
=> chore: Updating notation-core-go dependency to rc.3

go.mod, go.sum, registry/internal/artifactspec/artifact.go, registry/repository.go, registry/repository_test.go
=> build: bump image-spec to v1.1.0-rc.3 and oras-go to v2.1.0

example_localSign_test.go, example_localVerify_test.go, example_remoteVerify_test.go, internal/mock/mocks.go, notation_test.go, registry/interface.go, registry/repository.go, registry/repository_test.go
This PR removes notation-go `Sign`'s support of OCI artifact manifest as it is removed from [image-spec v1.0.0-rc.3](https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc.3). In other words, Notation will only generate signatures stored as OCI image manifest in the future.
(Note: Notation can still consume signatures already stored as OCI artifact manifest for backwards compatibility.)
Related issue: https://github.com/notaryproject/notation/issues/660
=> update: removed Sign with OCI artifact manifest

README.md, internal/pkix/pkix.go, plugin/proto/verify.go, verifier/trustpolicy/trustpolicy.go, verifier/trustpolicy/trustpolicy_test.go, verifier/verifier_test.go
In this PR:
1. According to issue #287, updated `Notary v2` to `Notation`.
2. Updated error messages of trust policy to improve user experience. Related issue: https://github.com/notaryproject/notation/issues/621
Resolves #287
=> chore: running some chores for notation-go

internal/mock/mocks.go, notation.go, notation_test.go
This PR updates error message of `errExceededMaxVerificationLimit` to be more user friendly.
=> fix: updated error message of errExceededMaxVerificationLimit

notation.go, notation_test.go
This PR adds digest check on Sign.
Signed-off-by: Byron Chien <byronc@ucla.edu>
Co-authored-by: Patrick Zheng <patrickzheng@microsoft.com>
=> fix: add digest check for Sign

config/base.go, config/base_test.go, verifier/trustpolicy/trustpolicy.go, verifier/trustpolicy/trustpolicy_test.go
Added validations to make sure singingkeys.json, trustpolicy.json and config.json doesnt read's symlink
closes https://github.com/notaryproject/notation/issues/634
=> feat: add validations for symlink

verifier/verifier.go, verifier/verifier_test.go
updated timeout for OCSP call to 2 seconds.
Updates based on updates in https://github.com/notaryproject/notaryproject/pull/249
=> fix: update timeout for OCSP call to 2 seconds

signer/plugin.go, verifier/verifier.go
Changes in this PR:
1. `signer.NewFromPlugin(plugin plugin.SignPlugin, ...)`
2. `verifer.executePlugin(ctx context.Context, installedPlugin plugin.VerifyPlugin, ...)`
=> fix: quick fix to use correct sign/verify plugin

go.mod, go.sum
bump up `notation-core-go` from `v1.0.0-rc.4` to `v1.0.0`.
=> bump: upgrade notation-core-go to v1.0.0

go.mod, go.sum, registry/repository.go, registry/repository_test.go
- Update oras-go to v2.3.0.
- Replace oras.Pack() with oras.PackManifest() as it is deprecated in v2.3.0.
- Generate an empty config blob manually, as oras.PackManifest() does not generate the config blob with the notation artifact type as the media type.
Resolves #346 
=> bump: update oras-go to v2.3.0

plugin/manager.go, plugin/manager_test.go
This PR adds `Uninstall` method to `CLIManager`.
=> feat: add uninstall to CLIManager

internal/file/file.go, internal/file/file_test.go, internal/semver/semver.go, internal/semver/semver_test.go, plugin/errors.go, plugin/manager.go, plugin/manager_test.go, plugin/manager_unix.go, plugin/manager_windows.go, plugin/plugin.go, plugin/plugin_test.go, verifier/helpers.go, verifier/verifier.go
This PR adds the `Install` method to `plugin.CLIManager`.
As suggested by @shizhMSFT: 
when plugin path is a dir which contains a plugin executable file and extra files such as lib files and LICENSE files, all these files will be installed. A dir is considered a valid input if and only if `it contains one and only one valid plugin executable file named with format notaiton-{plugin-name}`. 
Note: only regular files under the dir will be installed, sub-directories are ignored.
If the input plugin path is just a single executable file, this file will be installed.
When plugin already exists:
1. If `overwrite` is set, version check is skipped. If the existing plugin is malfunctioning, directly overwrite it. If the existing plugin is valid, its plugin metadata is also returned for callers to …
=> feat: add install method to plugin CLIManager

plugin/manager.go, plugin/manager_test.go, plugin/manager_unix.go, plugin/manager_windows.go, plugin/plugin.go, plugin/plugin_test.go
This PR is the 2nd iteration of plugin install.
Installation SHOULD pass in any of the following scenario:
1. Installing a single valid plugin executable file on file system. An example can be `notation-com.example.plugin` on `Unix` and `notation-com.example.plugin.exe` on `Windows`.
2. Installing from a dir which contains `one and only one` executable file with file name in the `notation-{plugin-name}` format.
3. On `Unix`, install from a dir which contains `no executable file`, however, there's `one and only one` candidate file with file name in the `notation-{plugin-name}` format. (Notation would set it to executable and try install it with a warning alert to the user). On `Windows`, install would fail in this case since '.exe' file extension is required.
Corresponding tests are added …
=> feat: plugin install iteration 2

plugin/errors.go, plugin/manager.go, plugin/manager_test.go, plugin/plugin.go, plugin/plugin_test.go
- added `PluginUnknownError`, `PluginValidityError`, `PluginDirectoryError`. For each error types, Notation CLI should provide a recommanded suggestion to solve them.
- improved error message
Resolve part of: https://github.com/notaryproject/notation/issues/824
Resolve part of: https://github.com/notaryproject/notation/issues/867
=> fix: improve plugin error message

plugin/errors.go, plugin/manager.go, plugin/plugin.go, plugin/plugin_test.go
=> fix: update PluginExecutableFileError type

signer/plugin.go
Previous:
```
Warning: Always sign the artifact using digest(@sha256:...) rather than a tag(:v2) because tags are mutable and a tag reference can point to a different artifact than the one signed.
Error: describe-key command failed: failed to execute the describe-key command for plugin azure-kv: CertificateNotFound: A certificate with (name/id) self-signed-pkcs13/versions/70747b2064c0488e936eba7a29acc4c6 was not found in this key vault. If you recently deleted this certificate you may be able to recover it using the correct recovery command. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125182
```
Current:
```
Warning: Always sign the artifact using digest(@sha256:...) rather than a tag(:v2) because tags are mutable and a tag reference can point to a …
```
=> fix: update error message

plugin/proto/algorithm.go, plugin/proto/errors.go, plugin/proto/metadata.go, plugin/proto/proto.go, plugin/proto/sign.go, plugin/proto/verify.go
Change list:
* updated/added deprecation message.
* Also removed usage of deprecated types in `algorithms.go` file
=> chore: updated/added deprecation message

example_localSign_test.go, example_remoteSign_test.go, notation.go, notation_test.go, signer/plugin.go, signer/plugin_test.go, signer/signer.go, signer/signer_test.go
This PR adds support for signing blobs.
* This PR is ready for review**
=> feat: add support for signing blob

go.mod, go.sum, registry/repository.go
bumping up oras-go to v2.5.0 along with golang version to v1.21.
=> bump: bump golang and dependency versions

go.mod, go.sum
=> bump: bump up notation-core-go v1.0.3

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/license-checker.yml
To enable a safe way to create a release branch, we need to enable CI for the release branch as proposed in #408 
=> ci: enable ci for release branch

example_localSign_test.go, example_remoteSign_test.go, log/log_test.go, notation.go, notation_test.go, signer/plugin.go, signer/plugin_test.go, signer/signer.go, signer/signer_test.go
Revert:
- reverted #379 
- reverted test cases: `TestSignOptsMissingSignatureMediaType` and `TestSignOptsUnknownMediaType`, introduced in #405
Test:
- added test for `log` package to pass 80% coverage target
This reverts commit ec42378613e1e189da0e94f1c225dba0b06a0fed.
Resolves part of #412 
=> revert: "feat: add support for signing blob (#379)"

go.mod, go.sum, verifier/verifier.go, verifier/verifier_test.go
This PR updates the use of `SignerInfo.AuthenticSigningTime` due to upgrade of notation-core-go.
=> fix: fix usage of SignerInfo.AuthenticSigningTime

go.mod, go.sum
Bumping up notation-core-go to `v1.1.0-beta.1`.
=> bump: bump up notation-core-go

internal/pkix/pkix.go, internal/pkix/pkix_test.go, verifier/trustpolicy/trustpolicy_test.go
=> feat: support distinguished name state(S)

go.mod, go.sum, verifier/timestamp_test.go, verifier/verifier.go, verifier/verifier_test.go
This PR makes refactoring of revocation with the updated notation-core-go.
=> refactor!: update revocation based on notation-core-go

signer/signer.go
This would mean tagging a6ca9ee64a8e13bd4a45439c3d389d9fb59bdd19 as `v1.2.0` to release.
We need at least `4` approvals from `6` maintainers to release `notation-go v1.2.0`.
* bump: bump up for v1.2.0 release by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/442
https://github.com/notaryproject/notation-go/compare/v1.2.0-rc.1...a6ca9ee64a8e13bd4a45439c3d389d9fb59bdd19
=> bump: release v1.2.0

.github/workflows/build.yml, go.mod, go.sum, signer/signer.go
For maintaining `release-1.1` branch:
Fix: 
- updated SigningAgent to be "notation-go/v1.1.2+unreleased"
- updated codecov workflow to include secret for updating coverage statistic
Bump:
- updated dependencies
- updated Golang v1.22
=> fix&bump: maintenance update for branch `release-1.1`

go.mod, go.sum, signer/signer.go
This PR targets on main branch.
=> bump: bump up notation-core-go and signingAgent

dir/fs.go, dir/fs_test.go, dir/path.go, dir/path_test.go
This PR is for `release-1.2` branch only.
This PR cherry picks the fix of issue #446 from main.
The fix:
- Removed the `init()` function from `dir/path`
- When `userConfigDir()` returns an error, instead of `panic(err)`, default to the current directory instead
- Split `loadUserPath()` into two new functions used to setup and return the values for `UserConfigDir` and `UserLibexecDir`
- Added additional unit tests for the two new functions and to test the default directory is used when `HOME` is set to `""`
=> fix: dir no longer panics when HOME and XDG_CONFIG_HOME are not set

dir/fs.go, dir/fs_test.go, dir/path.go, dir/path_test.go
This PR addresses the issue https://github.com/notaryproject/notation-go/issues/446 for `release-1.1` branch
This commit was cherry picked from commit 4d76f9a41595021b71b5d36559a29e8def50aa47
In this PR I:
- I removed the `init()` function from `dir/path`
- When `userConfigDir()` returns an error, instead of `panic(err)` I
default to the current directory instead
- Split `loadUserPath()` into two new functions used to setup and return
the values for `UserConfigDir` and `UserLibexecDir`
- Added additional unit tests for the two new functions and to test the
default directory is used when `HOME` is set to `""`
=> fix: dir no longer panics when HOME and XDG_CONFIG_HOME are not set (#449) 

signer/signer.go
This would mean tagging e6dde2dc5f0b04ccbdaa241e5ab6f716ff7e1944 as `v1.2.1` to release.
We need at least `4` approvals from `6` maintainers to release `notation-go v1.2.1`.
* bump: release v1.2.0 by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/445
* fix: dir no longer panics when HOME and XDG_CONFIG_HOME are not set by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/451
https://github.com/notaryproject/notation-go/compare/v1.2.0...e6dde2dc5f0b04ccbdaa241e5ab6f716ff7e1944
=> bump: release v1.2.1

go.mod, go.sum, verifier/verifier.go, verifier/verifier_test.go
=> feat: crl support

dir/fs.go, dir/fs_test.go, dir/path.go, dir/path_test.go, go.mod, go.sum, internal/file/file.go, internal/file/file_test.go, verifier/crl/crl.go, verifier/crl/crl_test.go, verifier/verifier.go
This PR adds an implementation of CRL cache along with {NOTATION_CACHE} directory for callers to initialize the cache.
=> feat: crl cache

internal/pkix/fuzz_test.go
Adds a fuzz test from cncf-fuzzing: https://github.com/cncf/cncf-fuzzing/blob/main/projects/notary/fuzz_pkix_test.go
=> test: add fuzz test

signer/signer.go
This would mean tagging 26f491ea7d4455753c2d6b941177906e39145141 as `v1.3.0-rc.1` to release.
We need at least `4` approvals from `6` maintainers to release `notation-go v1.3.0-rc.1`.
* build(deps): bump golang.org/x/mod from 0.19.0 to 0.20.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/433
* build(deps): bump golang.org/x/crypto from 0.25.0 to 0.26.0 by @dependabot in https://github.com/notaryproject/notation-go/pull/434
* bump: upgrade golang to v1.22 by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/440
* docs: create release checklist on main by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/443
* bump: bump up notation-core-go and signingAgent by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/444
* fix: dir …
=> bump: release v1.3.0-rc.1

notation.go, notation_test.go, verifier/verifier.go
This PR updates logs.
Resolves #430. Also should resolve issue https://github.com/notaryproject/notation/issues/1004.
=> chore: update logs

verifier/crl/crl.go, verifier/crl/crl_test.go
This PR removes redundant logs in crl cache `Get` and `Set` methods. Instead, these logs should be logged in Notation CLI, see https://github.com/notaryproject/notation/pull/1078 for reference.
This PR also fixes a couple of error messages in crl cache.
=> fix: crl cache log and err msg

.github/.codecov.yml, example_signWithTimestmap_test.go, go.mod, go.sum, notation.go, signer/signer.go, signer/signer_test.go
This PR adds an option to enable tsa cert chain revocation check during signing.
Resolves #483
=> fix: enable timestamping cert chain revocation check during signing

notation.go, verifier/verifier.go
Fix:
- replaced `.String()` with the `%v` format to avoid rendering the string before actually logging it.
Resolves #480
=> perf(log): encode objects only when logged

go.mod, go.sum
bumping up notation-core-go and tspclient-go.
=> bump: bump up dependencies

notation.go, notation_test.go, verifier/verifier.go
This PR is for branch `release-1.3`.
=> chore: backport #469 for updating logs

go.mod, go.sum
This PR targets on `release-1.3` branch.
=> bump: bump up notation-core-go for `release-1.3` branch

internal/io/limitedwriter.go, internal/io/limitedwriter_test.go, plugin/plugin.go
Fix:
- set the plugin output limit for STDOUT and STDERR to be 10MiB
Test:
- when the plugin output size exceeds 64MiB, the output pipe breaks, and the plugin process outputs an error to STDERR
Spec changes: https://github.com/notaryproject/specifications/pull/320
Resolves #187
=> fix: limit the plugin output size

internal/io/limitedwriter.go, internal/io/limitedwriter_test.go, plugin/plugin.go
This PR is for `release-1.3` branch.
=> fix: cherry pick fix of plugin output size (#484) to release-1.3 branch

signer/signer.go
This would mean tagging c3c9bcdcf3db56c9a920188639006f340551e737 as `v1.3.0-rc.2` to release.
We need at least `4` approvals from `6` maintainers to release `notation-go v1.3.0-rc.2`.
* bump: release v1.3.0-rc.1 by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/465
* chore: cherry pick fixes from `main` by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/487
* chore: backport #469 for updating logs by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/489
* bump: bump up notation-core-go for `release-1.3` branch by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/490
* bump: bump up crypto for release-1.3 branch by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/493
* fix: cherry pick fix of plugin output …
=> bump: release v1.3.0-rc.2

go.mod, go.sum
This PR targets on `release-1.3` branch.
=> bump: bump up dependencies for release-1.3 branch

signer/signer.go
This would mean tagging 31ee0d664a21dccc77175f4b1e736d3a90231fe4 as `v1.3.0` to release.
We need at least `4` approvals from `6` maintainers to release `notation-go v1.3.0`.
* bump: release v1.3.0-rc.2 by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/495
* cherry-pick: cherry pick from main to release-1.3 branch by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/505
* bump: bump up dependencies for release-1.3 branch by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/506
https://github.com/notaryproject/notation-go/compare/v1.3.0-rc.2...31ee0d664a21dccc77175f4b1e736d3a90231fe4
=> bump: release v1.3.0

example_verifyBlob_test.go, verifier/verifier.go, verifier/verifier_test.go
This PR moves optional parameters of the verifier constructor into `VerifierOptions`.
=> refactor: updated verifier constructor

verifier/timestamp_test.go, verifier/verifier.go
This PR removes the signing time check against timestamp during authentic timestamp verification. The possibility of time skew requires further discussion on the check.
Resolves: #513
=> fix: remove signing time check during authenticTimestamp

signer/signer.go
This would mean tagging 961cef1f72d86e8f564bf7790fe04b23af53f02e as `v1.3.1` to release.
We need at least `4` approvals from `6` maintainers to release `notation-go v1.3.1`.
* bump: release v1.3.0 by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/507
* fix: remove signing time check during authenticTimestamp by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/514
* bump: bump up dependencies for release-1.3 branch by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/516
https://github.com/notaryproject/notation-go/compare/v1.3.0...961cef1f72d86e8f564bf7790fe04b23af53f02e
=> bump: release v1.3.1

verifier/timestamp_test.go, verifier/verifier.go
This PR removes the timestamping check against signing time during authenticTimestamp verification. This is due to potential time skew and signing time is considered unauthenticated per Notary Project spec: https://github.com/notaryproject/specifications/blob/main/specs/signature-specification.md#standard-attributes.
=> fix: timestamp against signing time

example_remoteSign_test.go, example_signWithTimestmap_test.go, notation.go, notation_test.go
Feat:
- added `SignOCI` function and **deprecated** the `Sign` function to return both artifact and signature manifest descriptor.
Fix:
- handled referrer index deletion error as a warning to avoid confusion about the final signing status.
Resolve part of https://github.com/notaryproject/notation/issues/695
=> feat: add `SignOCI` function to return both artifact and signature manifest descriptor

errors.go, errors_test.go
This PR fixes https://github.com/notaryproject/notation-go/issues/528 and adds the following changes:
- add new custom errors (naming aligned with [Go convention](https://go.dev/doc/effective_go#errors))
- mark old custom error deprecated
=> refactor: update error names to align with Go convention

example_localVerify_test.go, example_remoteVerify_test.go, example_verifyWithTimestamp_test.go, notation_test.go
This PR fixes a part of `staticcheck` complains reported in  https://github.com/notaryproject/notation-go/issues/531 
The remaining issues will be addressed in a separate PRs.
=> fix: staticcheck complains - replace deprecated functions

signer/signer.go
This would mean tagging 34a1aba2261cbe97b597ec96e440a61f6aadc416 as `v1.3.2` to release.
We need at least `4` approvals from `6` maintainers to release `notation-go v1.3.2`.
* bump: release v1.3.1 by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/517
* backport: from main to release-1.3 branch by @Two-Hearts in https://github.com/notaryproject/notation-go/pull/536
https://github.com/notaryproject/notation-go/compare/v1.3.1...34a1aba2261cbe97b597ec96e440a61f6aadc416
* @qba73 made their first contribution in https://github.com/notaryproject/notation-go/pull/529
=> bump: release v1.3.2

signer/plugin.go, signer/plugin_test.go
=> fix: remove generate-envelope plugin support for blob signing
