notaryproject/notation-go

- CODEOWNERS
- CODE_OF_CONDUCT.md
- README.md
Add CODEOWNERS file based on project maintainers defined [here]((https://github.com/theupdateframework/notary/blob/master/MAINTAINERS#L23-L27)).
> Add codeowners

- CODE_OF_CONDUCT.md
- README.md
Updating README with code of conduct file
Signed-off-by: Terence Truong <Terence.Truong@microsoft.com>
> Adding information and links to README.md

- notation.go
- signature/jws/signer.go
- signature/jws/signer_test.go
- signature/jws/verifier_test.go
> Timestamp per signing

- verification/store.go
- verification/store_test.go
Signed-off-by: rgnote <5878554+rgnote@users.noreply.github.com>
> Fix trust store tests issue on Windows

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/test.yml
- .gitignore
- Makefile
- scripts/test.sh
Signed-off-by: Lixia (Sylvia) Lei <lixia_lei@outlook.com>
> Run unit tests in Github workflow

- .github/workflows/add-to-project.yml
Add all new issues to the notary project tracking board
> add to project template

- plugin/manager/manager.go
- plugin/plugin.go
Signed-off-by: Jonathan Donas <jddonas@amazon.com>
> Add command shapes for verify-signature and get-plugin-metadata

- registry/interface.go
- registry/repository.go
> resolving remote signature envelope digest as blob instead of manifest

- go.mod
- go.sum
- plugin/plugin.go
- signature/plugin.go
This PR is related to this PR https://github.com/notaryproject/notation-core-go/pull/20 and this issue https://github.com/notaryproject/notation/issues/268.
> hash name fix

- registry/repository.go
- registry/repository_test.go
Add unit tests for the `registry` package.
Resolves https://github.com/notaryproject/notation-go/issues/69
Signed-off-by: Binbin Li <libinbin@microsoft.com>
> test: add registry unit test

- go.mod
- go.sum
- notation.go
- registry/interface.go
- registry/repository.go
- signature/provider.go
- signature/verifier.go
1. Bug fix
2. Update verifier to use new package
3. Use verify opts to show the envelope media type
> refactor:support cose verify and signature push

- go.mod
- go.sum
- signature/envelope.go
- signature/plugin.go
- signature/provider.go
- signature/signer.go
- verification/types.go
- verification/verifier.go
- verification/verifier_helpers.go
1. Validate signature format
2. save keySpec and certchain to external plugin's member field
3. Bug fix and doc
4. Add method for inspecting signature format
5. Add signing scheme parameter
> refactor:notation-go support cose

- go.mod
- registry/mediatype.go
- registry/repository_test.go
- signature/algorithm_test.go
- signature/envelope.go
- signature/envelope_test.go
- signature/plugin.go
- signature/provider.go
- signature/signer_test.go
- signature/verifier_test.go
1. Fix broken unit tests except plugin_test.go, provider_test.go and files under verification package
2. Test all signing algorithms for signer test and verifier test
3. add algorithm test and envelope test
> test:fix broken unit test and add more test cases

- signature/plugin_test.go
- signature/provider.go
> test:fix plugin tests

- go.mod
- go.sum
> refactor:update dependency

- config/config.go
- config/config_test.go
- config/testdata/config.json
Resolve: https://github.com/notaryproject/notation/issues/325
> config add envelope type argument

- go.mod
update go.mod
Test
unit test work well
Resolves #99 
> feat: update to go 1.18

- config/config_test.go
- config/keys_test.go
- go.mod
1. fix config  unit test
2. update go version
> fix: fix config unit test

- go.mod
> feat: update to go 1.18 (#124)

- config/config.go
- config/keys.go
- dir/fs.go
> fix: comment typo

- verification/policy.go
- verification/policy_test.go
- verification/store_test.go
> fix: fix verification unit test

- config/config.go
- config/config_test.go
- config/testdata/config.json
> fix: rename envelopeType to signatureFormat

- go.mod
- go.sum
> updating notation-core-go to v0.2.0-beta.1

- internal/mock/mocks.go
- notation_test.go
Replaced the old internal/plugin with new plugin package in notation package
> refactor: update plugin for notation package

- internal/container/set.go
- verifier/helpers.go
This PR adds a generic Set data structure into the library.
Resolves #203.
> Add: added set data structure

- notation.go
- verifier/verifier.go
> fix: optimize verification level skip check

- plugin/plugin.go
Improving debug log for plugin
> Improving debug log for plugin

- .gitignore
- internal/pkix/pkix.go
- notation.go
- registry/repository_test.go
- verifier/helpers.go
- verifier/trustpolicy/trustpolicy.go
- verifier/trustpolicy/trustpolicy_test.go
- verifier/verifier_test.go
This PR targets on issues #251, #252 and #254.
> chore: logs and tests clean-up

- go.mod
> chore: updated to go 1.19

- internal/mock/mocks.go
- notation.go
- notation_test.go
This PR adds digest check on verify.
> fix: added digest check on verify

- verifier/verifier.go
Fix:
- added warning message for non-revokable certificate
> fix: add warning message for non-revokable certificate

- go.mod
- go.sum
This PR is for `release-1.3` branch.
> bump: bump up crypto for release-1.3 branch

- verifier/verifier.go
This PR improves log readability of the library.
> chore(verifier): improve log

- config/errors.go
- config/errors_test.go
- config/keys.go
- config/keys_test.go
- plugin/errors.go
This PR contains some error message enhancements found while using the library.
> fix: update error message for signing key config

- README.md
This PR adds OpenSSF scorecard to the README
> chore: show openssf scorecard
